### ISSUE TITLE
Intra Badge

### ISSUE THREAD

**Issue by TheoPaesch** [42core-team/event#1]
![image](https://github.com/42core-team/event/assets/147173090/79008e39-f644-4daf-8205-a1b26cb6b30b)
![image](https://github.com/42core-team/event/assets/147173090/94cb60df-f7e6-4aa7-9e01-33a8c0f07473)

**Comment by TheoPaesch** [comment]
> KING OF THE CORE for king of the hill CORE ARENA CHAMPION CORE COLLOSEUM CHAMPION CORE COLLOSEUM CONQUEROR CONQUEROR OF THE CORE KING OF THE NEW META CORE COMMODUS

@TheoPaesch @FelixBrgm @PaulicStudios @JonasGoetz01 @Reptudn 

bitte abstimmen

**Comment by Reptudn** [comment]
> KING OF THE CORE for king of the hill
> CORE ARENA CHAMPION
> CORE COLLOSEUM CHAMPION
> CORE COLLOSEUM CONQUEROR
> CONQUEROR OF THE CORE
> KING OF THE NEW META
> CORE COMMODUS
> 
> 

Also ich fände CORE CHAMPION am einfachsten obwohl sich die anderen auch nicht schlecht anhören

**Comment by TheoPaesch** [comment]
frage ist halt auch, ob das so "zulässig" ist, wenn da überall core drin steht wie das curriculum

**Comment by TheoPaesch** [comment]
was wäre mit C.O.R.E, was für conqueror of regional event steht

**Comment by PaulicStudios** [comment]
CORE COMMODUS
